### ISSUE TITLE
Config for http2

### ISSUE THREAD

**Issue by skynet** [tollmanz/wphttp#1]
Doesn't look like you've added config for http2.

**Comment by tollmanz** [comment]
All the config is present. 
- nginx: https://github.com/tollmanz/wphttp/blob/master/conf/etc/nginx/sites/http2.wphttp.com.conf
- nghttpx: https://github.com/tollmanz/wphttp/blob/master/conf/etc/nghttpx/nghttpx.conf

**Comment by tollmanz** [comment]
I plan to add more information in the future. There are a lot of gaps in knowledge about how to actually set this up.

**Comment by skynet** [comment]
I don't see a `listen 443 ssl http2` here: https://github.com/tollmanz/wphttp/blob/master/conf/etc/nginx/sites/http2.wphttp.com.conf#L2

From NGINX (http://nginx.org/en/docs/http/ngx_http_v2_module.html) docs:

```
server {
    listen 443 ssl http2;

    ssl_certificate server.crt;
    ssl_certificate_key server.key;
}
```

**Comment by skynet** [comment]
Was just curious if you make use of the additional directives, optimizing for http2. http://nginx.org/en/docs/http/ngx_http_v2_module.html

**Comment by tollmanz** [comment]
I'm using nghttpx as a reverse proxy in front of nginx. nghttpx is responsible for terminating TLS and handling HTTP/2. It then passes the request to nginx via port 80 for handling the WordPress stuff.

browser => nghttpx 443 => nginx 80 => php-fpm => WordPress

Does that make sense? While not specific to this setup, I've gone into using nghttpx as a proxy for nginx here: https://www.tollmanz.com/http2-nghttp2-nginx-tls/.

Again, I plan to add more docs to this soon. I might even use nginx's built in HTTP/2 support (which launched on Tuesday!), which would change things quite a bit.

**Comment by skynet** [comment]
Yes, it does make sense. thanks for sharing all this info. We're using NGINX here as a reverse proxy. Do you know if [1.9.5](http://nginx.org/en/docs/http/ngx_http_v2_module.html) supports [Server Push](https://http2.github.io/faq/#how-can-i-use-http2-server-push)?

**Comment by tollmanz** [comment]
Sadly, it does not :frowning: I decided to use nghttpx precisely so we could work with server push here.

**Comment by skynet** [comment]
Makes sense. NGINX will probably support server push in the next versions. Looks like you also managed to support both spdy and h2 here: https://spdycheck.org/#http2.wphttp.com
Wonder how can we do that with NGINX.

**Comment by tollmanz** [comment]
Nginx abandoned SPDY with the introduction of HTTP/2. Can't have both with Nginx. Nghttpx allows both SPDY and HTTP/2. Both Nghttpx and Nginx support [ALPN](https://en.wikipedia.org/wiki/Application-Layer_Protocol_Negotiation) so they can support HTTP/2 and HTTP/1.1. It's just that Nginx made the decision to not support SPDY and HTTP/2.

**Comment by skynet** [comment]
Just realized that and now having to downgrade a couple of servers to previous Nginx version.
